version: '3.7'

services:
  server:
    image: nginx
    restart: always
    env_file: stack.env
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      - ${IN5VOL}config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ${IN5VOL}docker/app/public:/var/www/app/public:ro
    depends_on:
      - app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    ports:
      - "8180:80"
      #- "443:443"

  app:
    image: invoiceninja/invoiceninja:5.6.5
    env_file: stack.env
    restart: always
    volumes:
      - ${IN5VOL}docker/app/public:/var/www/app/public:rw,delegated
      - ${IN5VOL}docker/app/storage:/var/www/app/storage:rw,delegated
    depends_on:
      - db

  db:
    image: lscr.io/linuxserver/mariadb:latest
    #container_name: invoicing_test_db
    env_file: stack.env
    volumes:
      - ${IN5VOL}db:/config
    restart: unless-stopped

networks:
  default:
    name: ${CONNET}
    external: true