version: '3.7'
services:
  server:
    image: lscr.io/linuxserver/nginx:1.24.0-r6-ls229
    env_file: stack.env
    volumes:
      - ${IN5VOL}web:/config
      - ${IN5VOL}in5-site.conf:/config/nginx/site-confs/in5-site.conf:ro
      #- ${IN5VOL}docker/app/public:/var/www/app/public:ro
      - ${IN5VOL}public:/config/www/app/public:rw,delegated
    restart: unless-stopped
    depends_on:
      - app
  app:
    image: invoiceninja/invoiceninja:5.6.5
    env_file: stack.env
    volumes:
      - ${IN5VOL}public:/var/www/app/public:rw,delegated
      - ${IN5VOL}storage:/var/www/app/storage:rw,delegated
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: lscr.io/linuxserver/mariadb:10.11.4-r0-ls103
    #container_name: invoicing_test_db
    env_file: stack.env
    volumes:
      - ${IN5VOL}db:/config
    restart: unless-stopped

networks:
  default:
    name: ${CONNET}
    external: true